### ISSUE TITLE
魔法哥的投票你来定（第一季六月月度评选）

### ISSUE THREAD

**Issue by cssmagic** [cssmagic/DApp-Dev-Group#6]
## 概述

群主（魔法哥）是星云激励计划的评审之一，拥有投票权。

第一季六月最佳应用正在评选中。群主准备了 200 票，完全交给社区（各位群友）来决定。

## 候选应用

应用代号 | 应用名称
---:|---
`A` | MonsterBlock Mega
`B` | 星图
`C` | NAS Tip Bot
`D` | GOLD Token
`E` | 四铢 (增强版)
`F` | Nebulas Cat 星云合约本地开发调试工具
`G` | 区块链摇号/摇奖系统
`H` | 星云应用商店
`I` | Game of Blocks
`J` | 星云水浒
`K` | 头号玩家—资本游戏
`L` | FixedEx - 去中心化交易所

## 活动方式

1. 群友在上面列出的 [六月份 12 款优秀应用](https://incentive.nebulas.io/cn/vote.html#vote-list) 中选出自己最看好的 DApp，**每人可选两款**。

1. 在本 issue 下留言，留下你的投票意向。留言格式如下：

	> * 我所在的群： `DApp 开发魔法群 (4)`
	> * 我的群昵称： `王大锤` *（非群友留言无效）*
	> * 我的地址： `n1xxxxxxxxxxxxxxxx`
	> * 我最看好的应用： `K` 和 `F` *（仅可填写上面表格中的 “应用代号”，每人最多选两款应用）*
	> * 我的 VIP 编号： `1088` *（普通群友可不填）*

1. 本周三（7 月 18 日）晚 9 点截止留言。

1. 群主根据群友的有效留言，统计出投票意向，把 200 票按比例投出。

1. 群主从意向最高的应用开始投票。如果在官方规则的有效投票时间内 200 票仍未投完，将停止投票。

## 奖励方式

本活动的目的是把投票权开放给 **社区全体成员**，鼓励大家 **共同行使投票权**。为感谢大家的认真参与，设立小额奖励。

* 在所有猜中最终冠军的留言中，根据留言顺序取前五名（不足五人则取实际数量），每人获 1 NAS 奖励。
* 在所有猜中最终亚军的留言中，根据留言顺序取前五名（不足五人则取实际数量），每人获 0.5 NAS 奖励。
* 在所有猜中最终季军的留言中，根据留言顺序取前五名（不足五人则取实际数量），每人获 0.2 NAS 奖励。
* 如果官方未公布来亚军和季军且无法考证，则相应奖励取消。
* **[VIP](https://github.com/cssmagic/DApp-Dev-Group/issues/1) 奖励翻倍**。

奖励将在星云官方公布评选结果后一周内发放。

***

<sup>* 另有约 100 票用于支持候选应用中的 Nasa 用户或有意向的潜在用户。</sup>

<sup>* 本文档的最终解释权属于群主。</sup>

**Comment by cssmagic** [comment]
...

**Comment by xieqing0428** [comment]
我所在的群： DApp VIP 魔法群
我的群昵称： 听泉
我的地址： n1HUHaFqmrJqPr6tRbmwfkKUD5qBy1KKFD3
我最看好的应用： F
我的 VIP 编号： 1016

**Comment by liufuhu** [comment]
我所在的群： DApp 开发魔法群2
我的群昵称： 阿虎
我的地址： n1awbmTUxcS6wQS9U6PCwdXgmpeVP7EoNfA
我最看好的应用： G

**Comment by huangang** [comment]
我所在的群： DApp VIP 魔法群
我的群昵称： zorro_ku_o
我的地址： n1Sr1JikGGdsxBCrKQdytecbdepwUWtBL7k
我最看好的应用： J
我的 VIP 编号： 1020

**Comment by yeyifen** [comment]
我所在的群： DApp 开发魔法群❸
我的群昵称： 陨夜天星
我的地址： n1UJzJT66pRB25UEBxAvCtJcEEeoUEeBsDb
我最看好的应用： L 和 G

**Comment by overwhats** [comment]
我所在的群： DApp VIP 魔法群
我的群昵称： 人间
我的地址： n1ahATdEBY9PPepVBpMUJKA3SxnAmnAHnKb
我最看好的应用： J 和 G
我的 VIP 编号： 1008

**Comment by yuzexia** [comment]
我所在的群： DApp 开发魔法群1
我的群昵称： 夏语择
我的地址： n1PxSG2Wh6yPA4qHUQ24Lz38iPurniMBRgg
我最看好的应用： J 和 G
我的 VIP 编号： 1018

**Comment by chengbotao** [comment]
我所在的群： DApp VIP 魔法群
我的群昵称： CXuan
我的地址： n1ZMaUo3dHzLtQBM4jrVNMbdbP2ije4ga7n
我最看好的应用： F 和 J
我的 VIP 编号： 1013

**Comment by getive** [comment]
我所在的群：DApp VIP 魔法群
我的群昵称： 痛饮狂歌
我的地址： n1c7jPNKtbnwf3RdTNnPUDCpadvuRRduUiJ
我最看好的应用： G 和 H
我的 VIP 编号： 1004

**Comment by newraina** [comment]
我所在的群： DApp VIP 魔法群
我的群昵称： newraina
我的地址： n1JCrwtxFncexo87pLC4SSCqV7HZCnHoHJ2
我最看好的应用： H 和 K
我的 VIP 编号： 1003

**Comment by yujiayinshi** [comment]
我所在的群： DApp 开发魔法群 (1)
我的群昵称： 黄凯
我的地址： n1dDtZ6BdSLa3Auh7VN1LsNVU1ZCcfN9f2s
我最看好的应用： B 和 H
我的 VIP 编号： 1025

**Comment by cssmagic** [comment]
群友投票结束～

**Comment by cssmagic** [comment]
投票汇总：

| 应用 | 应用 | 群友票数 | 换算 NAS 票数
|:---:|:---:|---:|---:
`B` | 星图 | 1 | 12
`F` | Nebulas Cat | 2 | 24
`G` | 区块链摇号/摇奖系统 | 5 | 59
`H` | 星云应用商店 | 3 | 36
`J` | 星云水浒 | 4 | 48
`K` | 头号玩家—资本游戏 | 1 | 12
`L` | FixedEx - 去中心化交易所 | 1 | 12
| |
| | 合计 | 17 | 203

**Comment by cssmagic** [comment]
### 官方排名

![rank](https://user-images.githubusercontent.com/1231359/43046291-39524d06-8df9-11e8-9ca1-bc6d5db5c41f.png)

***

### 第一名：头号玩家

猜中的群友（每人奖励 1 NAS，VIP 奖励翻倍）： 

* @newraina `n1JCrwtxFncexo87pLC4SSCqV7HZCnHoHJ2` => 1 NAS x 2

### 第二名：四铢

猜中的群友： （无）

### 第三名：星云应用商店

猜中的群友（每人奖励 0.2 NAS，VIP 奖励翻倍）：

* @getive  `n1c7jPNKtbnwf3RdTNnPUDCpadvuRRduUiJ` => 0.2 NAS x 2
* @newraina  `n1JCrwtxFncexo87pLC4SSCqV7HZCnHoHJ2` => 0.2 NAS x 2
* @yujiayinshi `n1dDtZ6BdSLa3Auh7VN1LsNVU1ZCcfN9f2s` => 0.2 NAS x 2
